### ISSUE TITLE
Cannot make 2026.03.05 for Arch 6.19.14

### ISSUE THREAD

**Issue by sshaikh** [strongtz/i915-sriov-dkms#441]
```
❯ uname -a
Linux dev 6.19.14-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 23 Apr 2026 06:57:02 +0000 x86_64 GNU/Linux
```

While building module:

```
...
  CC [M]  drivers/gpu/drm/xe/display/intel_fbdev_fb.o
drivers/gpu/drm/i915/i915_gem.c: In function ‘ggtt_write’:
drivers/gpu/drm/i915/i915_gem.c:523:21: error: implicit declaration of function ‘__copy_from_user_inatomic_nocache’; did you mean ‘__c
opy_from_user_inatomic’? [-Wimplicit-function-declaration]
  523 |         unwritten = __copy_from_user_inatomic_nocache((void __force *)vaddr + offset,
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                     __copy_from_user_inatomic
make[4]: *** [/usr/lib/modules/6.19.14-arch1-1/build/scripts/Makefile.build:289: drivers/gpu/drm/i915/i915_gem.o] Error 1
make[4]: *** Waiting for unfinished jobs....
  CC [M]  drivers/gpu/drm/xe/display/xe_display.o
  CC [M]  drivers/gpu/drm/xe/display/xe_display_misc.o
  CC [M]  drivers/gpu/drm/xe/display/xe_display_rpm.o
  CC [M]  drivers/gpu/drm/xe/display/xe_display_wa.o
make[3]: *** [/usr/lib/modules/6.19.14-arch1-1/build/scripts/Makefile.build:546: drivers/gpu/drm/i915] Error 2
make[3]: *** Waiting for unfinished jobs....
  CC [M]  drivers/gpu/drm/xe/display/xe_dsb_buffer.o
...
```

Seemed to work ok on 6.19.13

**Comment by sshaikh** [comment]
Changing `__copy_from_user_inatomic_nocache` to `__copy_from_user_inatomic` fixed this for me.

**Comment by bbaa-bbaa** [comment]
Please use the kernel-v6.19 branch from https://github.com/strongtz/i915-sriov-dkms/tree/kernel-v6.19
