### PR TITLE
Changed the signature of `drm_dp_calc_pbn_mode`

### LINKED ISSUE #151: install error on pve 8.1 kernel version : 6.5.13-5
CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/i915_sriov_sysfs.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/gt/iov/intel_iov.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/gt/iov/intel_iov_debugfs.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/gt/iov/intel_iov_event.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/gt/iov/intel_iov_memirq.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/gt/iov/intel_iov_provisioning.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/gt/iov/intel_iov_query.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/gt/iov/intel_iov_relay.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/gt/iov/intel_iov_service.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/gt/iov/intel_iov_state.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/gt/iov/intel_iov_sysfs.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/hsw_ips.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_atomic.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_atomic_plane.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_audio.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_bios.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_bw.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_cdclk.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_color.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_combo_phy.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_connector.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_crtc.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_crtc_state_dump.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_cursor.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_display.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_display_power.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_display_power_map.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_display_power_well.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_dmc.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_dpio_phy.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_dpll.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_dpll_mgr.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_dpt.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_drrs.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_dsb.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_fb.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_fb_pin.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_fbc.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_fdi.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_fifo_underrun.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_frontbuffer.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_global_state.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_hdcp.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_hotplug.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_hti.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_lpe_audio.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_modeset_verify.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_modeset_setup.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_overlay.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_pch_display.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_pch_refclk.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_plane_initial.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_psr.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_quirks.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_sprite.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_tc.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_vblank.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_vga.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/i9xx_plane.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/skl_scaler.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/skl_universal_plane.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/skl_watermark.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_acpi.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_opregion.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_fbdev.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/dvo_ch7017.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/dvo_ch7xxx.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/dvo_ivch.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/dvo_ns2501.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/dvo_sil164.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/dvo_tfp410.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/g4x_dp.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/g4x_hdmi.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/icl_dsi.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_backlight.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_crt.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_cx0_phy.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_ddi.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_ddi_buf_trans.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_display_trace.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_dkl_phy.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_dp.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_dp_aux.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_dp_aux_backlight.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_dp_hdcp.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_dp_link_training.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_dp_mst.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_dsi.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_dsi_dcs_backlight.o
  CC [M]  /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_dsi_vbt.o
/var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_dp_mst.c: In function ‘intel_dp_mst_find_vcpi_slots_for_bpp’:
/var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_dp_mst.c:86:35: error: too many arguments to function ‘drm_dp_calc_pbn_mode’
   86 |                 crtc_state->pbn = drm_dp_calc_pbn_mode(adjusted_mode->crtc_clock,
      |                                   ^~~~~~~~~~~~~~~~~~~~
In file included from /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_display_types.h:36,
                 from /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_dp_mst.c:40:
./include/drm/display/drm_dp_mst_helper.h:835:5: note: declared here
  835 | int drm_dp_calc_pbn_mode(int clock, int bpp);
      |     ^~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_dp_mst.c: In function ‘intel_dp_mst_mode_valid_ctx’:
/var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_dp_mst.c:906:17: error: too many arguments to function ‘drm_dp_calc_pbn_mode’
  906 |                 drm_dp_calc_pbn_mode(mode->clock, min_bpp, false) > port->full_pbn) {
      |                 ^~~~~~~~~~~~~~~~~~~~
./include/drm/display/drm_dp_mst_helper.h:835:5: note: declared here
  835 | int drm_dp_calc_pbn_mode(int clock, int bpp);
      |     ^~~~~~~~~~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:251: /var/lib/dkms/i915-sriov-dkms/6.5/build/drivers/gpu/drm/i915/display/intel_dp_mst.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [/usr/src/linux-headers-6.5.13-5-pve/Makefile:2039: /var/lib/dkms/i915-sriov-dkms/6.5/build] Error 2
make: *** [Makefile:234: __sub-make] Error 2
make: Leaving directory '/usr/src/linux-headers-6.5.13-5-pve'

### PR DESCRIPTION
**Pull request by makazeu**
**Prcoceeding with this merge may break builds in PVE with kernel < 6.5.13-5-pve**

Changed the signature of `drm_dp_calc_pbn_mode` to fix the install error on the PVE kernel `6.5.13-5-pve`

Applying this change can fix #151

### CODE REVIEW

**Comment by ravnoor** [comment]
Worked for me - thanks!

```bash
$ dkms install -m i915-sriov-dkms -v 6.5.13-5 -k 6.5.13-5-pve --force -j 1
dkms status
Sign command: /lib/modules/6.5.13-5-pve/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module:
Cleaning build area...
make -j1 KERNELRELEASE=6.5.13-5-pve -C /lib/modules/6.5.13-5-pve/build M=/var/lib/dkms/i915-sriov-dkms/6.5.13-5/build KVER=6.5.13-5-pve........................................................
Signing module /var/lib/dkms/i915-sriov-dkms/6.5.13-5/build/i915.ko
Cleaning build area...

i915.ko:
Running module version sanity check.
 - Original module
 - Installation
   - Installing to /lib/modules/6.5.13-5-pve/updates/dkms/
depmod...

$ dkms status
i915-sriov-dkms/6.5.13-5, 6.5.13-5-pve, x86_64: installed
```

```bash
$ lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation Raptor Lake-P [Iris Xe Graphics] (rev 04)
00:02.1 VGA compatible controller: Intel Corporation Raptor Lake-P [Iris Xe Graphics] (rev 04)
00:02.2 VGA compatible controller: Intel Corporation Raptor Lake-P [Iris Xe Graphics] (rev 04)
00:02.3 VGA compatible controller: Intel Corporation Raptor Lake-P [Iris Xe Graphics] (rev 04)
00:02.4 VGA compatible controller: Intel Corporation Raptor Lake-P [Iris Xe Graphics] (rev 04)
00:02.5 VGA compatible controller: Intel Corporation Raptor Lake-P [Iris Xe Graphics] (rev 04)
00:02.6 VGA compatible controller: Intel Corporation Raptor Lake-P [Iris Xe Graphics] (rev 04)
00:02.7 VGA compatible controller: Intel Corporation Raptor Lake-P [Iris Xe Graphics] (rev 04)
```

**Comment by jiaopengzi** [comment]
Worked for me too - thanks!
Applying this change can fix #154 

```
CPU:13th Gen Intel(R) Core(TM) i5-13400
Motherboard：B760M GAMING vendor:JGINYUE
memory:32GiB DIMM DDR4 Synchronous 3200 MHz (0.3 ns)
Linux pve 6.5.13-5-pve #1 SMP PREEMPT_DYNAMIC PMX 6.5.13-5 (2024-04-05T11:03Z) x86_64 GNU/Linux
```

**Comment by strongtz** [comment]
Could this be merged now maybe?

**Comment by muink** [comment]
Worked for me too - thanks!

**Comment by lalalamiheart** [comment]
`Building module:
Cleaning build area...
make -j1 KERNELRELEASE=6.5.13-5-pve -C /lib/modules/6.5.13-5-pve/build M=/var/lib/dkms/i915-sriov-dkms/6.5.13-5/build KVER=6.5.13-5-pve.........................................................................(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.5.13-5-pve (x86_64)
Consult /var/lib/dkms/i915-sriov-dkms/6.5.13-5/build/make.log for more information.`
`make[2]: *** [scripts/Makefile.build:251: /var/lib/dkms/i915-sriov-dkms/6.5.13-5/build/drivers/gpu/drm/i915/display/intel_dp_mst.o] Error 1
make[1]: *** [/usr/src/linux-headers-6.5.13-5-pve/Makefile:2039: /var/lib/dkms/i915-sriov-dkms/6.5.13-5/build] Error 2
make: *** [Makefile:234: __sub-make] Error 2
make: Leaving directory '/usr/src/linux-headers-6.5.13-5-pve'`

not work for me on pve6.5.13-5 and cpu n100.
is there any details that i could miss? And i tried to install it before, should i do something to fix it?

**Comment by bolzerrr** [comment]
I am also having issues to build with an n100 CPU

```
/var/lib/dkms/i915-sriov-dkms/6.5.13-3/build/drivers/gpu/drm/i915/display/intel_dp_mst.c: In function ‘intel_dp_mst_find_vcpi_slots_for_bpp’:
/var/lib/dkms/i915-sriov-dkms/6.5.13-3/build/drivers/gpu/drm/i915/display/intel_dp_mst.c:85:31: error: too few arguments to function ‘drm_dp_calc_pbn_mode’
   85 |             crtc_state->pbn = drm_dp_calc_pbn_mode(adjusted_mode->crtc_clock,
      |                               ^~~~~~~~~~~~~~~~~~~~
In file included from /var/lib/dkms/i915-sriov-dkms/6.5.13-3/build/drivers/gpu/drm/i915/display/intel_display_types.h:36,
                 from /var/lib/dkms/i915-sriov-dkms/6.5.13-3/build/drivers/gpu/drm/i915/display/intel_dp_mst.c:40:
./include/drm/display/drm_dp_mst_helper.h:835:5: note: declared here
  835 | int drm_dp_calc_pbn_mode(int clock, int bpp, bool dsc);
      |     ^~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/i915-sriov-dkms/6.5.13-3/build/drivers/gpu/drm/i915/display/intel_dp_mst.c: In function ‘intel_dp_mst_mode_valid_ctx’:
/var/lib/dkms/i915-sriov-dkms/6.5.13-3/build/drivers/gpu/drm/i915/display/intel_dp_mst.c:898:13: error: too few arguments to function ‘drm_dp_calc_pbn_mode’
  898 |             drm_dp_calc_pbn_mode(mode->clock, min_bpp) > port->full_pbn) {
      |             ^~~~~~~~~~~~~~~~~~~~
./include/drm/display/drm_dp_mst_helper.h:835:5: note: declared here
  835 | int drm_dp_calc_pbn_mode(int clock, int bpp, bool dsc);
      |     ^~~~~~~~~~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:251: /var/lib/dkms/i915-sriov-dkms/6.5.13-3/build/drivers/gpu/drm/i915/display/intel_dp_mst.o] Fehler 1
make[2]: *** Es wird auf noch nicht beendete Prozesse gewartet....
make[1]: *** [/usr/src/linux-headers-6.5.13-3-pve/Makefile:2039: /var/lib/dkms/i915-sriov-dkms/6.5.13-3/build] Fehler 2
make: *** [Makefile:234: __sub-make] Error 2
make: Leaving directory '/usr/src/linux-headers-6.5.13-3-pve'
```

**Comment by ifwwww** [comment]
Works for me too. Thanks！
`root@pve:~# lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation AlderLake-S GT1 (rev 0c)
00:02.1 VGA compatible controller: Intel Corporation AlderLake-S GT1 (rev 0c)
00:02.2 VGA compatible controller: Intel Corporation AlderLake-S GT1 (rev 0c)
00:02.3 VGA compatible controller: Intel Corporation AlderLake-S GT1 (rev 0c)
00:02.4 VGA compatible controller: Intel Corporation AlderLake-S GT1 (rev 0c)
00:02.5 VGA compatible controller: Intel Corporation AlderLake-S GT1 (rev 0c)
00:02.6 VGA compatible controller: Intel Corporation AlderLake-S GT1 (rev 0c)
00:02.7 VGA compatible controller: Intel Corporation AlderLake-S GT1 (rev 0c)`

**Comment by arf-it** [comment]
Hi,
Did anybody check if this will somehow fix the #137 issue? 
I was able to build the module against the 6.5.13-3 kernel, but it was not usable because of the memory leak when a container was using the GPU.

**Comment by makazeu** [comment]
> Could this be merged now maybe?

Hi @strongtz , sorry for the delayed response.

It seems OK to proceed with the merge from my perspective, although people might encounter difficulties building in a PVE with a kernel version lower than 6.5.13-5-pve.

How do you think on this issue? Do you this project to support relatively older PVE kernels?  Thanks

**Comment by strongtz** [comment]
> How do you think on this issue? Do you this project to support relatively older PVE kernels? Thanks

Is it possible to add a simple kernel version check to limit the fix to only PVE 6.5 kernels?

**Comment by xbb** [comment]
> > How do you think on this issue? Do you this project to support relatively older PVE kernels? Thanks
> 
> Is it possible to add a simple kernel version check to limit the fix to only PVE 6.5 kernels?

See https://github.com/strongtz/i915-sriov-dkms/issues/151#issuecomment-2057571630

I don't know if there are other methods

**Comment by herokillerJ** [comment]
Worked for me - thanks!

**Comment by johntdavis84** [comment]
Hello!

Thanks for your work on this. Do we need to pin the kernel to 6.5.13_3?

I'm running into some build issues with the latest kernel, and wanted to check if maybe it's just too new.
```
pveversion -v
proxmox-ve: 8.1.0 (running kernel: 6.5.13-1-pve)
pve-manager: 8.1.4 (running version: 8.1.4/ec5affc9e41f1d79)
proxmox-kernel-helper: 8.1.0
proxmox-kernel-6.5.13-1-pve-signed: 6.5.13-1
proxmox-kernel-6.5: 6.5.13-1
proxmox-kernel-6.5.11-8-pve-signed: 6.5.11-8
```

Thanks!
