### ISSUE TITLE
PVE9.19  7.0.0-3-pve Error! Bad return status for module build on kernel: 7.0.0-3-pve (x86_64)

### ISSUE THREAD

**Issue by 35598253** [strongtz/i915-sriov-dkms#445]
dpkg -i /tmp/i915-sriov-dkms_2026.05.03_amd64.deb
(Reading database ... 89980 files and directories currently installed.)
Preparing to unpack .../i915-sriov-dkms_2026.05.03_amd64.deb ...
Unpacking i915-sriov-dkms (2026.05.03) over (2026.05.03) ...
Setting up i915-sriov-dkms (2026.05.03) ...
Loading new i915-sriov-dkms/2026.05.03 DKMS files...
Building for 7.0.0-3-pve

Building initial module i915-sriov-dkms/2026.05.03 for 7.0.0-3-pve
Sign command: /lib/modules/7.0.0-3-pve/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module(s)...(bad exit status: 2)
Failed command:
make -j28 KERNELRELEASE=7.0.0-3-pve -C /lib/modules/7.0.0-3-pve/build M=/var/lib/dkms/i915-sriov-dkms/2026.05.03/build

Error! Bad return status for module build on kernel: 7.0.0-3-pve (x86_64)
Consult /var/lib/dkms/i915-sriov-dkms/2026.05.03/build/make.log for more information.
update-initramfs: Generating /boot/initrd.img-7.0.0-3-pve
Running hook script 'zz-proxmox-boot'..
Re-executing '/etc/kernel/postinst.d/zz-proxmox-boot' in new private mount namespace..
No /etc/kernel/proxmox-boot-uuids found, skipping ESP sync.

**sed -n '1,220p' /var/lib/dkms/i915-sriov-dkms/2026.05.03/build/make.log**
DKMS (dkms-3.2.2) make.log for i915-sriov-dkms/2026.05.03 for kernel 7.0.0-3-pve (x86_64)
Sun May  3 08:55:47 AM CST 2026

Building module(s)
# command: make -j28 KERNELRELEASE=7.0.0-3-pve -C /lib/modules/7.0.0-3-pve/build M=/var/lib/dkms/i915-sriov-dkms/2026.05.03/build
make: Entering directory '/usr/src/linux-headers-7.0.0-3-pve'
make[1]: Entering directory '/var/lib/dkms/i915-sriov-dkms/2026.05.03/build'
warning: pahole version differs from the one used to build the kernel
  The kernel was built with: 130
  You are using:             0
  CONFTEST copy_from_user_inatomic_nontemporal
sh: 0: cannot open ././conftest.sh: No such file
  CC [M]  compat/v6.18/drm_gpuvm.o
  CC [M]  compat/v6.18/drm_ttm_bo.o
  CC [M]  compat/v6.19/drm_dp_helper.o
  CC [M]  compat/v6.19/pci_rebar.o
  CC [M]  compat/v7.0/dmabuf_dma_fence.o
  CC [M]  compat/v7.0/drm_dp_helper.o
  CC [M]  compat/v7.0/drm_sched_main.o
  HOSTCC  drivers/gpu/drm/xe/xe_gen_wa_oob
  CC [M]  compat/drm_gpusvm.o
  CC [M]  compat/drm_pagemap.o
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
  CC [M]  compat/drm_pagemap_util.o
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
  CC [M]  compat/main.o
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
  CC [M]  drivers/gpu/drm/i915/i915_config.o
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
  CC [M]  drivers/gpu/drm/i915/i915_driver.o
  CC [M]  drivers/gpu/drm/i915/i915_drm_client.o
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
  CC [M]  drivers/gpu/drm/i915/i915_edram.o
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
  CC [M]  drivers/gpu/drm/i915/i915_freq.o
  CC [M]  drivers/gpu/drm/i915/i915_getparam.o
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
  CC [M]  drivers/gpu/drm/i915/i915_gmch.o
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
  CC [M]  drivers/gpu/drm/i915/i915_ioctl.o
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
  CC [M]  drivers/gpu/drm/i915/i915_irq.o
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
  CC [M]  drivers/gpu/drm/i915/i915_mitigations.o
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
  CC [M]  drivers/gpu/drm/i915/i915_mmio_range.o
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
  CC [M]  drivers/gpu/drm/i915/i915_module.o
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
  CC [M]  drivers/gpu/drm/i915/i915_params.o
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
  CC [M]  drivers/gpu/drm/i915/i915_pci.o
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
  CC [M]  drivers/gpu/drm/i915/i915_scatterlist.o
make[4]: *** [/usr/src/linux-headers-7.0.0-3-pve/scripts/Makefile.build:289: drivers/gpu/drm/i915/i915_mmio_range.o] Error 1
make[4]: *** Waiting for unfinished jobs....
  GEN     xe_wa_oob.c xe_wa_oob.h
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
  GEN   xe_device_wa_oob.c xe_device_wa_oob.h
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
  CC [M]  drivers/gpu/drm/xe/xe_bb.o
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
  CC [M]  drivers/gpu/drm/xe/xe_bo.o
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
  CC [M]  drivers/gpu/drm/xe/xe_bo_evict.o
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
make[4]: *** [/usr/src/linux-headers-7.0.0-3-pve/scripts/Makefile.build:289: compat/v7.0/dmabuf_dma_fence.o] Error 1
make[4]: *** Waiting for unfinished jobs....
  CC [M]  drivers/gpu/drm/xe/xe_dep_scheduler.o
make[4]: *** [/usr/src/linux-headers-7.0.0-3-pve/scripts/Makefile.build:289: drivers/gpu/drm/i915/i915_config.o] Error 1
  CC [M]  drivers/gpu/drm/xe/xe_devcoredump.o
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
make[4]: *** [/usr/src/linux-headers-7.0.0-3-pve/scripts/Makefile.build:289: compat/v7.0/drm_sched_main.o] Error 1
  CC [M]  drivers/gpu/drm/xe/xe_device.o
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
make[4]: *** [/usr/src/linux-headers-7.0.0-3-pve/scripts/Makefile.build:289: compat/drm_pagemap_util.o] Error 1
  CC [M]  drivers/gpu/drm/xe/xe_device_sysfs.o
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
make[4]: *** [/usr/src/linux-headers-7.0.0-3-pve/scripts/Makefile.build:289: compat/main.o] Error 1
  CC [M]  drivers/gpu/drm/xe/xe_dma_buf.o
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
make[4]: *** [/usr/src/linux-headers-7.0.0-3-pve/scripts/Makefile.build:289: compat/drm_gpusvm.o] Error 1
  CC [M]  drivers/gpu/drm/xe/xe_drm_client.o
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
make[4]: *** [/usr/src/linux-headers-7.0.0-3-pve/scripts/Makefile.build:289: compat/v6.19/pci_rebar.o] Error 1
  CC [M]  drivers/gpu/drm/xe/xe_eu_stall.o
make[4]: *** [/usr/src/linux-headers-7.0.0-3-pve/scripts/Makefile.build:289: compat/v6.18/drm_gpuvm.o] Error 1
  CC [M]  drivers/gpu/drm/xe/xe_exec.o
make[4]: *** [/usr/src/linux-headers-7.0.0-3-pve/scripts/Makefile.build:289: compat/v7.0/drm_dp_helper.o] Error 1
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
  CC [M]  drivers/gpu/drm/xe/xe_exec_queue.o
make[4]: *** [/usr/src/linux-headers-7.0.0-3-pve/scripts/Makefile.build:289: drivers/gpu/drm/i915/i915_scatterlist.o] Error 1
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
  CC [M]  drivers/gpu/drm/xe/xe_execlist.o
make[4]: *** [/usr/src/linux-headers-7.0.0-3-pve/scripts/Makefile.build:289: compat/v6.18/drm_ttm_bo.o] Error 1
make[4]: *** [/usr/src/linux-headers-7.0.0-3-pve/scripts/Makefile.build:289: compat/drm_pagemap.o] Error 1
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
  CC [M]  drivers/gpu/drm/xe/xe_force_wake.o
  CC [M]  drivers/gpu/drm/xe/xe_ggtt.o
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
make[4]: *** [/usr/src/linux-headers-7.0.0-3-pve/scripts/Makefile.build:289: compat/v6.19/drm_dp_helper.o] Error 1
make[3]: *** [/usr/src/linux-headers-7.0.0-3-pve/scripts/Makefile.build:548: compat] Error 2
make[3]: *** Waiting for unfinished jobs....
  CC [M]  drivers/gpu/drm/xe/xe_gpu_scheduler.o
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
make[4]: *** [/usr/src/linux-headers-7.0.0-3-pve/scripts/Makefile.build:289: drivers/gpu/drm/i915/i915_freq.o] Error 1
  CC [M]  drivers/gpu/drm/xe/xe_gsc.o
make[4]: *** [/usr/src/linux-headers-7.0.0-3-pve/scripts/Makefile.build:289: drivers/gpu/drm/i915/i915_getparam.o] Error 1
  CC [M]  drivers/gpu/drm/xe/xe_gsc_debugfs.o
make[4]: *** [/usr/src/linux-headers-7.0.0-3-pve/scripts/Makefile.build:289: drivers/gpu/drm/i915/i915_gmch.o] Error 1
  CC [M]  drivers/gpu/drm/xe/xe_gsc_proxy.o
make[4]: *** [/usr/src/linux-headers-7.0.0-3-pve/scripts/Makefile.build:289: drivers/gpu/drm/i915/i915_ioctl.o] Error 1
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
  CC [M]  drivers/gpu/drm/xe/xe_gsc_submit.o
make[4]: *** [/usr/src/linux-headers-7.0.0-3-pve/scripts/Makefile.build:289: drivers/gpu/drm/i915/i915_mitigations.o] Error 1
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_
  CC [M]  drivers/gpu/drm/xe/xe_gt.o
In file included from <command-line>:
./././conftest/results.h:2: error: unterminated #ifndef
    2 | #ifndef _INTEL_DRM_BACKPORT_CONFTEST_H_

**Comment by slyang40** [comment]
+1, having the same issue.

**Comment by bbaa-bbaa** [comment]
Ah, it looks like I forgot to add the new conftest.sh to the packaging script. My mistake.
I'll release the fix version as soon as possible.

**Comment by bbaa-bbaa** [comment]
Re-released the related release tag with a force push (a bit messy, hope it didn't affect anyone xD)

The CI tests didn't use the package installation path. Apologies for not noticing that.

**Comment by jay-kub** [comment]
The updated release fixed the issue for me. Thanks for the quick fix my friend.

**Comment by luckman212** [comment]
I got "hit" with this yesterday, hastily rebooted my PVE 9.19 node without spotting the module build error (missing conftest.sh) and got a PSOD (Kernel Panic). Had to do recovery. Got it all sorted luckily. May try again later, but had enough of a scare to keep me off the latest release for a bit longer. Thanks for fixing :pray:

**Comment by bbaa-bbaa** [comment]
Theoretically, a failed DKMS build won't modify your system, the kernel will simply fall back to the stock driver. Sorry again for the inconvenience caused.

**Comment by rickgitdone** [comment]
used the latest build today (May 4) on Ubuntu 24.04 ... 

Kernel: 6.17.0-23-generic (Ubuntu 24.04)
Package: i915-sriov-dkms 2026.05.03
CPU: Intel i7-13700
GPU: UHD 770 (Raptor Lake-S)

Build fails with:
drivers/gpu/drm/i915/i915_gem.c:524:21: error: implicit declaration 
of function 'copy_from_user_inatomic_nontemporal'

Root cause: conftest.sh incorrectly defines 
IDB_COPY_FROM_USER_INATOMIC_NONTEMPORAL=1 on 6.17 even though the 
function was removed. The #else fallback 
__copy_from_user_inatomic_nocache is available in 6.17.

Fix: Comment out the #ifdef block in i915_gem.c lines ~520-530 
and use __copy_from_user_inatomic_nocache directly.

With this change above we got a clean build for i915 and xe .. dkms installed...

**Comment by Cycloctane** [comment]
> used the latest build today (May 4) on Ubuntu 24.04 ...
> 
> Kernel: 6.17.0-23-generic (Ubuntu 24.04) Package: i915-sriov-dkms 2026.05.03 CPU: Intel i7-13700 GPU: UHD 770 (Raptor Lake-S)
> 
> Root cause: conftest.sh incorrectly defines
> IDB_COPY_FROM_USER_INATOMIC_NONTEMPORAL=1 on 6.17 even though the
> function was removed.

Reapplying #443 patch can avoid this error.

**Comment by Tay-lordd** [comment]
Hello. I'm not following how to apply the patch. Shouldn't this be fixed from the source?

Kernel: 6.17.0-23-generic (Ubuntu 24.04)

Error! Bad return status for module build on kernel: 6.17.0-14-generic (x86_64)

drivers/gpu/drm/i915/i915_gem.c:524:21: error: implicit declaration of function ‘copy_from_user_inatomic_nontemporal’ [-Werror=implicit-function-declaration]
  524 |         unwritten = copy_from_user_inatomic_nontemporal((void __force *)vaddr + offset,

**Comment by luckman212** [comment]
I installed 2026.05.03 today on my pve node running kernel 6.17.13-6 (not 7.0 yet) and it's working, thank you

**Comment by Tay-lordd** [comment]
> Hello. I'm not following how to apply the patch. Shouldn't this be fixed from the source?
> 
> Kernel: 6.17.0-23-generic (Ubuntu 24.04)
> 
> Error! Bad return status for module build on kernel: 6.17.0-14-generic (x86_64)
> 
> drivers/gpu/drm/i915/i915_gem.c:524:21: error: implicit declaration of function ‘copy_from_user_inatomic_nontemporal’ [-Werror=implicit-function-declaration] 524 | unwritten = copy_from_user_inatomic_nontemporal((void __force *)vaddr + offset,

2026.05.06 has resolved this issue for me. Thanks!
